<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Concrete</title>
  <meta name="description" content="Concrete" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Concrete" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Concrete" />
  
  
  



<meta name="date" content="2025-10-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path=""><a href="#analisis-univariado"><i class="fa fa-check"></i><b>1</b> Analisis Univariado</a>
<ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#resistencia"><i class="fa fa-check"></i><b>1.1</b> Resistencia</a></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#cemento"><i class="fa fa-check"></i><b>1.2</b> Cemento</a></li>
<li class="chapter" data-level="1.3" data-path=""><a href="#residuo"><i class="fa fa-check"></i><b>1.3</b> Residuo</a></li>
<li class="chapter" data-level="1.4" data-path=""><a href="#ceniza"><i class="fa fa-check"></i><b>1.4</b> Ceniza</a></li>
<li class="chapter" data-level="1.5" data-path=""><a href="#agua"><i class="fa fa-check"></i><b>1.5</b> Agua</a></li>
<li class="chapter" data-level="1.6" data-path=""><a href="#superplastificante"><i class="fa fa-check"></i><b>1.6</b> Superplastificante</a></li>
<li class="chapter" data-level="1.7" data-path=""><a href="#grueso"><i class="fa fa-check"></i><b>1.7</b> Grueso</a></li>
<li class="chapter" data-level="1.8" data-path=""><a href="#fino"><i class="fa fa-check"></i><b>1.8</b> Fino</a></li>
<li class="chapter" data-level="1.9" data-path=""><a href="#d%C3%ADas"><i class="fa fa-check"></i><b>1.9</b> Días</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path=""><a href="#preparaci%C3%B3n-de-los-datos"><i class="fa fa-check"></i><b>2</b> Preparación de los datos</a>
<ul>
<li class="chapter" data-level="2.1" data-path=""><a href="#carga-del-dataframe"><i class="fa fa-check"></i><b>2.1</b> Carga del dataframe</a></li>
<li class="chapter" data-level="2.2" data-path=""><a href="#nombres-originales-de-las-columnas"><i class="fa fa-check"></i><b>2.2</b> Nombres Originales de las Columnas</a></li>
<li class="chapter" data-level="2.3" data-path=""><a href="#renombramiento-de-variables"><i class="fa fa-check"></i><b>2.3</b> Renombramiento de Variables</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path=""><a href="#an%C3%A1lisis-de-correlaciones"><i class="fa fa-check"></i><b>3</b> Análisis de Correlaciones</a>
<ul>
<li class="chapter" data-level="3.1" data-path=""><a href="#resistencia-vs-cemento"><i class="fa fa-check"></i><b>3.1</b> Resistencia vs Cemento</a></li>
<li class="chapter" data-level="3.2" data-path=""><a href="#resistencia-vs-residuos"><i class="fa fa-check"></i><b>3.2</b> Resistencia vs Residuos</a></li>
<li class="chapter" data-level="3.3" data-path=""><a href="#resistencia-vs-cenizas"><i class="fa fa-check"></i><b>3.3</b> Resistencia vs Cenizas</a></li>
<li class="chapter" data-level="3.4" data-path=""><a href="#resistencia-vs-agua"><i class="fa fa-check"></i><b>3.4</b> Resistencia vs Agua</a></li>
<li class="chapter" data-level="3.5" data-path=""><a href="#resistencia-vs-superplastificante"><i class="fa fa-check"></i><b>3.5</b> Resistencia vs Superplastificante</a></li>
<li class="chapter" data-level="3.6" data-path=""><a href="#resistencia-vs-grueso"><i class="fa fa-check"></i><b>3.6</b> Resistencia vs Grueso</a></li>
<li class="chapter" data-level="3.7" data-path=""><a href="#resistencia-vs-fino"><i class="fa fa-check"></i><b>3.7</b> Resistencia vs Fino</a></li>
<li class="chapter" data-level="3.8" data-path=""><a href="#resistencia-vs-dias"><i class="fa fa-check"></i><b>3.8</b> Resistencia vs Dias</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path=""><a href="#conclusiones"><i class="fa fa-check"></i><b>4</b> Conclusiones</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Concrete</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Concrete</h1>
<p class="date"><em>2025-10-20</em></p>
</div>
<div id="analisis-univariado" class="section level2 hasAnchor" number="1">
<h2><span class="header-section-number">1</span> Analisis Univariado<a href="#analisis-univariado" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="resistencia" class="section level3 hasAnchor" number="1.1">
<h3><span class="header-section-number">1.1</span> Resistencia<a href="#resistencia" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a>Concrete <span class="sc">%&gt;%</span> </span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(Concrete[[<span class="dv">9</span>]]),</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(Concrete[[<span class="dv">9</span>]]),</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(Concrete[[<span class="dv">9</span>]]),</span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(Concrete[[<span class="dv">9</span>]]),</span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(Concrete[[<span class="dv">9</span>]]),</span>
<span id="cb1-8"><a href="#cb1-8" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(Concrete[[<span class="dv">9</span>]]),</span>
<span id="cb1-9"><a href="#cb1-9" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(Concrete[[<span class="dv">9</span>]], <span class="fl">0.25</span>),</span>
<span id="cb1-10"><a href="#cb1-10" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(Concrete[[<span class="dv">9</span>]], <span class="fl">0.75</span>),</span>
<span id="cb1-11"><a href="#cb1-11" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(Concrete[[<span class="dv">9</span>]])</span>
<span id="cb1-12"><a href="#cb1-12" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>##      n    media       ds mediana minimo maximo    Q1     Q3    IQR
## 1 1030 35.81796 16.70574  34.445   2.33   82.6 23.71 46.135 22.425</code></pre>
<p>La variable Compressive Strength fue analizada a partir de 1.030 observaciones. Se obtuvo una resistencia promedio de aproximadamente 35,82 MPa (DS = 16,71 MPa), donde el 50% de las muestras presentan resistencias por debajo de 34,45 MPa. El mínimo registrado fue de 2,33 MPa, lo que indica mezclas de concreto muy jóvenes (posiblemente evaluadas a 1 día de curado) o con proporciones poco óptimas de ingredientes. Por su parte, el máximo alcanzó los 82,6 MPa, lo cual refleja mezclas de alta resistencia con composiciones especiales, mayor contenido de cemento, uso de superplastificantes y tiempos de curado prolongados (hasta 365 días según el dataset).
El rango intercuartílico (IQR = 22,43 MPa) muestra una variabilidad considerable, con el primer cuartil (Q1) en 23,71 MPa y el tercer cuartil (Q3) en 46,14 MPa. Esta dispersión confirma que la resistencia del concreto está fuertemente influenciada por la combinación de factores como la dosificación de cemento, la presencia de materiales suplementarios (escoria y ceniza volante), la relación agua-cemento y, especialmente, la edad de curado.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="co"># Histograma con curva de densidad</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a><span class="fu">ggplot</span>(Concrete, <span class="fu">aes</span>(<span class="at">x =</span> Concrete[[<span class="dv">9</span>]])) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), </span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;steelblue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-7"><a href="#cb3-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución de la Resistencia a la Compresión del Concreto&quot;</span>,</span>
<span id="cb3-8"><a href="#cb3-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Resistencia a la Compresión (MPa)&quot;</span>,</span>
<span id="cb3-9"><a href="#cb3-9" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Densidad&quot;</span>,</span>
<span id="cb3-10"><a href="#cb3-10" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb3-11"><a href="#cb3-11" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb3-13"><a href="#cb3-13" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb3-14"><a href="#cb3-14" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb3-15"><a href="#cb3-15" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb3-16"><a href="#cb3-16" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb3-17"><a href="#cb3-17" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## Warning: Use of `Concrete[[9]]` is discouraged.
## ℹ Use `.data[[9]]` instead.
## Use of `Concrete[[9]]` is discouraged.
## ℹ Use `.data[[9]]` instead.</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" width="672" />
Se puede ver en el grafico la heterogenidad de los datos sin contar esa leve sesgo a la derecha lo que significa que las otras variables no deben estar influyendo de manera drastica en los estadísticos como la media y la desviación estándar</p>
</div>
<div id="cemento" class="section level3 hasAnchor" number="1.2">
<h3><span class="header-section-number">1.2</span> Cemento<a href="#cemento" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="fu">ggplot</span>(Concrete, <span class="fu">aes</span>(<span class="at">y =</span> Cement)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;coral&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb5-4"><a href="#cb5-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del Contenido de Cemento&quot;</span>,</span>
<span id="cb5-5"><a href="#cb5-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Cemento (kg/m³)&quot;</span>,</span>
<span id="cb5-6"><a href="#cb5-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb5-7"><a href="#cb5-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb5-9"><a href="#cb5-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb5-10"><a href="#cb5-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb5-11"><a href="#cb5-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb5-12"><a href="#cb5-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb5-13"><a href="#cb5-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a>Concrete <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(Cement),</span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(Cement),</span>
<span id="cb6-5"><a href="#cb6-5" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(Cement),</span>
<span id="cb6-6"><a href="#cb6-6" tabindex="-1"></a>    <span class="at">CV =</span> (<span class="fu">sd</span>(Cement) <span class="sc">/</span> <span class="fu">mean</span>(Cement)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb6-7"><a href="#cb6-7" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(Cement),</span>
<span id="cb6-8"><a href="#cb6-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(Cement),</span>
<span id="cb6-9"><a href="#cb6-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(Cement),</span>
<span id="cb6-10"><a href="#cb6-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(Cement, <span class="fl">0.25</span>),</span>
<span id="cb6-11"><a href="#cb6-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(Cement, <span class="fl">0.75</span>),</span>
<span id="cb6-12"><a href="#cb6-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(Cement)</span>
<span id="cb6-13"><a href="#cb6-13" tabindex="-1"></a>     </span>
<span id="cb6-14"><a href="#cb6-14" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>##      n    media       ds       CV mediana minimo maximo      Q1  Q3     IQR
## 1 1030 281.1679 104.5064 37.16867   272.9    102    540 192.375 350 157.625</code></pre>
<p>La variable Cement presenta una media de 281,17 kg/m³ (DS = 104,51 kg/m³) con un coeficiente de variación del 37,17%, indicando alta variabilidad en las dosificaciones. El rango oscila entre 102 kg/m³ (mezclas con bajo cemento, posiblemente compensadas con materiales suplementarios) y 540 kg/m³ (mezclas de alta resistencia para aplicaciones estructurales exigentes). La mediana de 272,9 kg/m³ y el IQR de 157,63 kg/m³ (Q1 = 192,38; Q3 = 350) revelan una distribución relativamente simétrica con algunos valores atípicos superiores. Esta amplia variabilidad refleja la diversidad de diseños de mezcla empleados en el dataset para lograr diferentes niveles de resistencia.</p>
</div>
<div id="residuo" class="section level3 hasAnchor" number="1.3">
<h3><span class="header-section-number">1.3</span> Residuo<a href="#residuo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">ggplot</span>(Concrete, <span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">Blast Furnace Slag</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;darkseagreen&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del Contenido de Escoria de Alto Horno&quot;</span>,</span>
<span id="cb8-5"><a href="#cb8-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Escoria de Alto Horno (kg/m³)&quot;</span>,</span>
<span id="cb8-6"><a href="#cb8-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb8-7"><a href="#cb8-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb8-10"><a href="#cb8-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb8-11"><a href="#cb8-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb8-12"><a href="#cb8-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb8-13"><a href="#cb8-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a>Concrete <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb9-3"><a href="#cb9-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(<span class="st">`</span><span class="at">Blast Furnace Slag</span><span class="st">`</span>),</span>
<span id="cb9-4"><a href="#cb9-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Blast Furnace Slag</span><span class="st">`</span>),</span>
<span id="cb9-5"><a href="#cb9-5" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(<span class="st">`</span><span class="at">Blast Furnace Slag</span><span class="st">`</span>),</span>
<span id="cb9-6"><a href="#cb9-6" tabindex="-1"></a>    <span class="at">CV =</span> (<span class="fu">sd</span>(<span class="st">`</span><span class="at">Blast Furnace Slag</span><span class="st">`</span>) <span class="sc">/</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Blast Furnace Slag</span><span class="st">`</span>)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb9-7"><a href="#cb9-7" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(<span class="st">`</span><span class="at">Blast Furnace Slag</span><span class="st">`</span>),</span>
<span id="cb9-8"><a href="#cb9-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(<span class="st">`</span><span class="at">Blast Furnace Slag</span><span class="st">`</span>),</span>
<span id="cb9-9"><a href="#cb9-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(<span class="st">`</span><span class="at">Blast Furnace Slag</span><span class="st">`</span>),</span>
<span id="cb9-10"><a href="#cb9-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Blast Furnace Slag</span><span class="st">`</span>, <span class="fl">0.25</span>),</span>
<span id="cb9-11"><a href="#cb9-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Blast Furnace Slag</span><span class="st">`</span>, <span class="fl">0.75</span>),</span>
<span id="cb9-12"><a href="#cb9-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(<span class="st">`</span><span class="at">Blast Furnace Slag</span><span class="st">`</span>)</span>
<span id="cb9-13"><a href="#cb9-13" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>##      n    media       ds       CV mediana minimo maximo Q1     Q3    IQR
## 1 1030 73.89583 86.27934 116.7581      22      0  359.4  0 142.95 142.95</code></pre>
<p>La variable Blast Furnace Slag presenta una media de 73,90 kg/m³ (DS = 86,28 kg/m³) con un coeficiente de variación del 116,76%, indicando una variabilidad extremadamente alta. La mediana de 22 kg/m³ es considerablemente menor que la media, revelando una marcada asimetría positiva. El rango oscila entre 0 kg/m³ (mezclas sin escoria) y 359,4 kg/m³ (mezclas con alto contenido de este material suplementario). El boxplot muestra que más del 50% de las muestras contienen cantidades bajas de escoria (Q1 = 0; Q3 = 142,95 kg/m³), con un valor atípico extremo alrededor de 360 kg/m³. Esta alta variabilidad refleja que la escoria es un ingrediente opcional utilizado selectivamente para mejorar propiedades específicas del concreto o reducir costos.</p>
</div>
<div id="ceniza" class="section level3 hasAnchor" number="1.4">
<h3><span class="header-section-number">1.4</span> Ceniza<a href="#ceniza" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="fu">ggplot</span>(Concrete, <span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">Fly Ash</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;lightskyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del Contenido de Ceniza Volante&quot;</span>,</span>
<span id="cb11-5"><a href="#cb11-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Ceniza Volante (kg/m³)&quot;</span>,</span>
<span id="cb11-6"><a href="#cb11-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb11-7"><a href="#cb11-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-8"><a href="#cb11-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb11-9"><a href="#cb11-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb11-10"><a href="#cb11-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb11-11"><a href="#cb11-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb11-12"><a href="#cb11-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb11-13"><a href="#cb11-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a>Concrete <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(<span class="st">`</span><span class="at">Fly Ash</span><span class="st">`</span>),</span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Fly Ash</span><span class="st">`</span>),</span>
<span id="cb12-5"><a href="#cb12-5" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(<span class="st">`</span><span class="at">Fly Ash</span><span class="st">`</span>),</span>
<span id="cb12-6"><a href="#cb12-6" tabindex="-1"></a>    <span class="at">CV =</span> (<span class="fu">sd</span>(<span class="st">`</span><span class="at">Fly Ash</span><span class="st">`</span>) <span class="sc">/</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Fly Ash</span><span class="st">`</span>)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb12-7"><a href="#cb12-7" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(<span class="st">`</span><span class="at">Fly Ash</span><span class="st">`</span>),</span>
<span id="cb12-8"><a href="#cb12-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(<span class="st">`</span><span class="at">Fly Ash</span><span class="st">`</span>),</span>
<span id="cb12-9"><a href="#cb12-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(<span class="st">`</span><span class="at">Fly Ash</span><span class="st">`</span>),</span>
<span id="cb12-10"><a href="#cb12-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Fly Ash</span><span class="st">`</span>, <span class="fl">0.25</span>),</span>
<span id="cb12-11"><a href="#cb12-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Fly Ash</span><span class="st">`</span>, <span class="fl">0.75</span>),</span>
<span id="cb12-12"><a href="#cb12-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(<span class="st">`</span><span class="at">Fly Ash</span><span class="st">`</span>)</span>
<span id="cb12-13"><a href="#cb12-13" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>##      n    media     ds      CV mediana minimo maximo Q1    Q3   IQR
## 1 1030 54.18835 63.997 118.101       0      0  200.1  0 118.3 118.3</code></pre>
<p>La variable Fly Ash presenta una media de 54,19 kg/m³ (DS = 64,00 kg/m³) con un coeficiente de variación del 118,10%, indicando una variabilidad extremadamente alta similar a la escoria. La mediana de 0 kg/m³ revela que al menos el 50% de las muestras no contienen ceniza volante, confirmando una marcada asimetría positiva. El rango oscila entre 0 kg/m³ (mezclas sin ceniza) y 200,1 kg/m³ (mezclas con alto contenido de este material puzolánico). El boxplot muestra que el 75% de las muestras tienen valores entre 0 y 118,3 kg/m³ (Q3), con un valor atípico alrededor de 200 kg/m³. Esta distribución indica que la ceniza volante, al igual que la escoria, es un ingrediente opcional utilizado selectivamente como material cementante suplementario para mejorar la durabilidad o reducir el costo del concreto.</p>
</div>
<div id="agua" class="section level3 hasAnchor" number="1.5">
<h3><span class="header-section-number">1.5</span> Agua<a href="#agua" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="fu">ggplot</span>(Concrete, <span class="fu">aes</span>(<span class="at">y =</span> Water)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del Contenido de Agua&quot;</span>,</span>
<span id="cb14-5"><a href="#cb14-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Agua (kg/m³)&quot;</span>,</span>
<span id="cb14-6"><a href="#cb14-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb14-7"><a href="#cb14-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb14-10"><a href="#cb14-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb14-11"><a href="#cb14-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb14-12"><a href="#cb14-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb14-13"><a href="#cb14-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a>Concrete <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-3"><a href="#cb15-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(Water),</span>
<span id="cb15-4"><a href="#cb15-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(Water),</span>
<span id="cb15-5"><a href="#cb15-5" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(Water),</span>
<span id="cb15-6"><a href="#cb15-6" tabindex="-1"></a>    <span class="at">CV =</span> (<span class="fu">sd</span>(Water) <span class="sc">/</span> <span class="fu">mean</span>(Water)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb15-7"><a href="#cb15-7" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(Water),</span>
<span id="cb15-8"><a href="#cb15-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(Water),</span>
<span id="cb15-9"><a href="#cb15-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(Water),</span>
<span id="cb15-10"><a href="#cb15-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(Water, <span class="fl">0.25</span>),</span>
<span id="cb15-11"><a href="#cb15-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(Water, <span class="fl">0.75</span>),</span>
<span id="cb15-12"><a href="#cb15-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(Water)</span>
<span id="cb15-13"><a href="#cb15-13" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>##      n    media       ds       CV mediana minimo maximo    Q1  Q3  IQR
## 1 1030 181.5673 21.35422 11.76105     185  121.8    247 164.9 192 27.1</code></pre>
<p>La variable Water presenta una media de 181,57 kg/m³ (DS = 21,35 kg/m³) con un coeficiente de variación del 11,76%, indicando baja variabilidad en comparación con otras variables. La mediana de 185 kg/m³ es cercana a la media, sugiriendo una distribución relativamente simétrica. El rango oscila entre 121,8 kg/m³ y 247 kg/m³, con un IQR reducido de 27,1 kg/m³ (Q1 = 164,9; Q3 = 192). El boxplot muestra algunos valores atípicos tanto superiores como inferiores, representando mezclas con relaciones agua-cemento extremas. Esta baja variabilidad refleja que el contenido de agua es un parámetro más controlado en el diseño de mezclas, ya que la relación agua-cemento es crítica para determinar la trabajabilidad y resistencia del concreto.</p>
</div>
<div id="superplastificante" class="section level3 hasAnchor" number="1.6">
<h3><span class="header-section-number">1.6</span> Superplastificante<a href="#superplastificante" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a><span class="fu">ggplot</span>(Concrete, <span class="fu">aes</span>(<span class="at">y =</span> Superplasticizer)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;plum&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb17-4"><a href="#cb17-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del Contenido de Superplastificante&quot;</span>,</span>
<span id="cb17-5"><a href="#cb17-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Superplastificante (kg/m³)&quot;</span>,</span>
<span id="cb17-6"><a href="#cb17-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb17-7"><a href="#cb17-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb17-9"><a href="#cb17-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb17-10"><a href="#cb17-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb17-11"><a href="#cb17-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb17-12"><a href="#cb17-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb17-13"><a href="#cb17-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a>Concrete <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb18-3"><a href="#cb18-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(Superplasticizer),</span>
<span id="cb18-4"><a href="#cb18-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(Superplasticizer),</span>
<span id="cb18-5"><a href="#cb18-5" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(Superplasticizer),</span>
<span id="cb18-6"><a href="#cb18-6" tabindex="-1"></a>    <span class="at">CV =</span> (<span class="fu">sd</span>(Superplasticizer) <span class="sc">/</span> <span class="fu">mean</span>(Superplasticizer)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb18-7"><a href="#cb18-7" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(Superplasticizer),</span>
<span id="cb18-8"><a href="#cb18-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(Superplasticizer),</span>
<span id="cb18-9"><a href="#cb18-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(Superplasticizer),</span>
<span id="cb18-10"><a href="#cb18-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(Superplasticizer, <span class="fl">0.25</span>),</span>
<span id="cb18-11"><a href="#cb18-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(Superplasticizer, <span class="fl">0.75</span>),</span>
<span id="cb18-12"><a href="#cb18-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(Superplasticizer)</span>
<span id="cb18-13"><a href="#cb18-13" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>##      n   media       ds       CV mediana minimo maximo Q1   Q3  IQR
## 1 1030 6.20466 5.973841 96.27991     6.4      0   32.2  0 10.2 10.2</code></pre>
<p>La variable Superplasticizer presenta una media de 6,20 kg/m³ (DS = 5,97 kg/m³) con un coeficiente de variación del 96,28%, indicando una variabilidad extremadamente alta. La mediana de 6,4 kg/m³ es cercana a la media, pero el mínimo de 0 kg/m³ revela que muchas mezclas no contienen este aditivo. El rango oscila entre 0 y 32,2 kg/m³, con un IQR de 10,2 kg/m³ (Q1 = 0; Q3 = 10,2). El boxplot muestra valores atípicos superiores alrededor de 28-32 kg/m³, representando mezclas de alto desempeño que requieren mayor fluidez. Esta distribución indica que el superplastificante es un aditivo químico opcional utilizado principalmente para mejorar la trabajabilidad del concreto sin aumentar el contenido de agua, siendo más común en mezclas de alta resistencia.</p>
</div>
<div id="grueso" class="section level3 hasAnchor" number="1.7">
<h3><span class="header-section-number">1.7</span> Grueso<a href="#grueso" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="fu">ggplot</span>(Concrete, <span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">Coarse Aggregate</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;tan&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-4"><a href="#cb20-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del Contenido de Agregado Grueso&quot;</span>,</span>
<span id="cb20-5"><a href="#cb20-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Agregado Grueso (kg/m³)&quot;</span>,</span>
<span id="cb20-6"><a href="#cb20-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb20-7"><a href="#cb20-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb20-10"><a href="#cb20-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb20-11"><a href="#cb20-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb20-12"><a href="#cb20-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb20-13"><a href="#cb20-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a>Concrete <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb21-3"><a href="#cb21-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(<span class="st">`</span><span class="at">Coarse Aggregate</span><span class="st">`</span>),</span>
<span id="cb21-4"><a href="#cb21-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Coarse Aggregate</span><span class="st">`</span>),</span>
<span id="cb21-5"><a href="#cb21-5" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(<span class="st">`</span><span class="at">Coarse Aggregate</span><span class="st">`</span>),</span>
<span id="cb21-6"><a href="#cb21-6" tabindex="-1"></a>    <span class="at">CV =</span> (<span class="fu">sd</span>(<span class="st">`</span><span class="at">Coarse Aggregate</span><span class="st">`</span>) <span class="sc">/</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Coarse Aggregate</span><span class="st">`</span>)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb21-7"><a href="#cb21-7" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(<span class="st">`</span><span class="at">Coarse Aggregate</span><span class="st">`</span>),</span>
<span id="cb21-8"><a href="#cb21-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(<span class="st">`</span><span class="at">Coarse Aggregate</span><span class="st">`</span>),</span>
<span id="cb21-9"><a href="#cb21-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(<span class="st">`</span><span class="at">Coarse Aggregate</span><span class="st">`</span>),</span>
<span id="cb21-10"><a href="#cb21-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Coarse Aggregate</span><span class="st">`</span>, <span class="fl">0.25</span>),</span>
<span id="cb21-11"><a href="#cb21-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Coarse Aggregate</span><span class="st">`</span>, <span class="fl">0.75</span>),</span>
<span id="cb21-12"><a href="#cb21-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(<span class="st">`</span><span class="at">Coarse Aggregate</span><span class="st">`</span>)</span>
<span id="cb21-13"><a href="#cb21-13" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>##      n    media       ds       CV mediana minimo maximo  Q1     Q3  IQR
## 1 1030 972.9189 77.75395 7.991822     968    801   1145 932 1029.4 97.4</code></pre>
<p>La variable Coarse Aggregate presenta una media de 972,92 kg/m³ (DS = 77,75 kg/m³) con un coeficiente de variación del 7,99%, indicando muy baja variabilidad. La mediana de 968 kg/m³ es prácticamente igual a la media, confirmando una distribución simétrica. El rango oscila entre 801 y 1145 kg/m³, con un IQR muy reducido de 97,4 kg/m³ (Q1 = 932; Q3 = 1029,4). El boxplot muestra ausencia de valores atípicos y una distribución muy compacta. Esta baja variabilidad refleja que el agregado grueso (grava) es un componente estructural esencial presente en cantidades relativamente constantes en todas las mezclas de concreto, representando típicamente el mayor volumen dentro de la composición y siendo crucial para la integridad estructural del material.</p>
</div>
<div id="fino" class="section level3 hasAnchor" number="1.8">
<h3><span class="header-section-number">1.8</span> Fino<a href="#fino" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="fu">ggplot</span>(Concrete, <span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">Fine Aggregate</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;sandybrown&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb23-4"><a href="#cb23-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del Contenido de Agregado Fino&quot;</span>,</span>
<span id="cb23-5"><a href="#cb23-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Agregado Fino (kg/m³)&quot;</span>,</span>
<span id="cb23-6"><a href="#cb23-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb23-7"><a href="#cb23-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb23-10"><a href="#cb23-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb23-11"><a href="#cb23-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb23-12"><a href="#cb23-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb23-13"><a href="#cb23-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a>Concrete <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb24-3"><a href="#cb24-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(<span class="st">`</span><span class="at">Fine Aggregate</span><span class="st">`</span>),</span>
<span id="cb24-4"><a href="#cb24-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Fine Aggregate</span><span class="st">`</span>),</span>
<span id="cb24-5"><a href="#cb24-5" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(<span class="st">`</span><span class="at">Fine Aggregate</span><span class="st">`</span>),</span>
<span id="cb24-6"><a href="#cb24-6" tabindex="-1"></a>    <span class="at">CV =</span> (<span class="fu">sd</span>(<span class="st">`</span><span class="at">Fine Aggregate</span><span class="st">`</span>) <span class="sc">/</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Fine Aggregate</span><span class="st">`</span>)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb24-7"><a href="#cb24-7" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(<span class="st">`</span><span class="at">Fine Aggregate</span><span class="st">`</span>),</span>
<span id="cb24-8"><a href="#cb24-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(<span class="st">`</span><span class="at">Fine Aggregate</span><span class="st">`</span>),</span>
<span id="cb24-9"><a href="#cb24-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(<span class="st">`</span><span class="at">Fine Aggregate</span><span class="st">`</span>),</span>
<span id="cb24-10"><a href="#cb24-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Fine Aggregate</span><span class="st">`</span>, <span class="fl">0.25</span>),</span>
<span id="cb24-11"><a href="#cb24-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Fine Aggregate</span><span class="st">`</span>, <span class="fl">0.75</span>),</span>
<span id="cb24-12"><a href="#cb24-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(<span class="st">`</span><span class="at">Fine Aggregate</span><span class="st">`</span>)</span>
<span id="cb24-13"><a href="#cb24-13" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>##      n    media       ds       CV mediana minimo maximo     Q1  Q3   IQR
## 1 1030 773.5805 80.17598 10.36427   779.5    594  992.6 730.95 824 93.05</code></pre>
<p>La variable Fine Aggregate presenta una media de 773,58 kg/m³ (DS = 80,18 kg/m³) con un coeficiente de variación del 10,36%, indicando baja variabilidad similar al agregado grueso. La mediana de 779,5 kg/m³ es cercana a la media, sugiriendo una distribución relativamente simétrica. El rango oscila entre 594 y 992,6 kg/m³, con un IQR de 93,05 kg/m³ (Q1 = 730,95; Q3 = 824). El boxplot muestra un valor atípico superior alrededor de 990 kg/m³, representando una mezcla con contenido excepcionalmente alto de arena. Esta baja variabilidad refleja que el agregado fino (arena) es otro componente estructural esencial presente en cantidades relativamente controladas en las mezclas de concreto, siendo fundamental para llenar los espacios vacíos entre el agregado grueso y lograr una matriz densa y trabajable.</p>
</div>
<div id="días" class="section level3 hasAnchor" number="1.9">
<h3><span class="header-section-number">1.9</span> Días<a href="#d%C3%ADas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a><span class="fu">ggplot</span>(Concrete, <span class="fu">aes</span>(<span class="at">y =</span> Age)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;tan&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-4"><a href="#cb26-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución de la Edad&quot;</span>,</span>
<span id="cb26-5"><a href="#cb26-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Edad (días)&quot;</span>,</span>
<span id="cb26-6"><a href="#cb26-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb26-7"><a href="#cb26-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-8"><a href="#cb26-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb26-9"><a href="#cb26-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb26-10"><a href="#cb26-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb26-11"><a href="#cb26-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb26-12"><a href="#cb26-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb26-13"><a href="#cb26-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a>Concrete <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb27-3"><a href="#cb27-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(Age),</span>
<span id="cb27-4"><a href="#cb27-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(Age),</span>
<span id="cb27-5"><a href="#cb27-5" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(Age),</span>
<span id="cb27-6"><a href="#cb27-6" tabindex="-1"></a>    <span class="at">CV =</span> (<span class="fu">sd</span>(Age) <span class="sc">/</span> <span class="fu">mean</span>(Age)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb27-7"><a href="#cb27-7" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(Age),</span>
<span id="cb27-8"><a href="#cb27-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(Age),</span>
<span id="cb27-9"><a href="#cb27-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(Age),</span>
<span id="cb27-10"><a href="#cb27-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(Age, <span class="fl">0.25</span>),</span>
<span id="cb27-11"><a href="#cb27-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(Age, <span class="fl">0.75</span>),</span>
<span id="cb27-12"><a href="#cb27-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(Age)</span>
<span id="cb27-13"><a href="#cb27-13" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>##      n    media       ds      CV mediana minimo maximo Q1 Q3 IQR
## 1 1030 45.66214 63.16991 138.342      28      1    365  7 56  49</code></pre>
<p>La edad del concreto en este estudio muestra una distribución altamente asimétrica, con el 75% de las muestras concentradas en 56 días o menos (mediana de 28 días) y un coeficiente de variación del 138% que indica gran dispersión. Se identifican tres valores atípicos excepcionales (180, 270 y 365 días). Esta distribución es estratégica porque el concreto desarrolla la mayor parte de su resistencia en los primeros 28 días, aunque las muestras de mayor edad son valiosas para evaluar el comportamiento a largo plazo. La edad será probablemente un predictor clave de la resistencia a la compresión, con una relación positiva esperada donde a mayor edad, mayor resistencia.</p>
</div>
</div>
<div id="preparación-de-los-datos" class="section level2 hasAnchor" number="2">
<h2><span class="header-section-number">2</span> Preparación de los datos<a href="#preparaci%C3%B3n-de-los-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="carga-del-dataframe" class="section level3 hasAnchor" number="2.1">
<h3><span class="header-section-number">2.1</span> Carga del dataframe<a href="#carga-del-dataframe" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;C:/Users/samit/Downloads/Concrete_Data.xls&quot;</span>)</span></code></pre></div>
</div>
<div id="nombres-originales-de-las-columnas" class="section level3 hasAnchor" number="2.2">
<h3><span class="header-section-number">2.2</span> Nombres Originales de las Columnas<a href="#nombres-originales-de-las-columnas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a><span class="fu">colnames</span>(df)</span></code></pre></div>
<pre><code>## [1] &quot;Cement (component 1)(kg in a m^3 mixture)&quot;            
## [2] &quot;Blast Furnace Slag (component 2)(kg in a m^3 mixture)&quot;
## [3] &quot;Fly Ash (component 3)(kg in a m^3 mixture)&quot;           
## [4] &quot;Water  (component 4)(kg in a m^3 mixture)&quot;            
## [5] &quot;Superplasticizer (component 5)(kg in a m^3 mixture)&quot;  
## [6] &quot;Coarse Aggregate  (component 6)(kg in a m^3 mixture)&quot; 
## [7] &quot;Fine Aggregate (component 7)(kg in a m^3 mixture)&quot;    
## [8] &quot;Age (day)&quot;                                            
## [9] &quot;Concrete compressive strength(MPa, megapascals)&quot;</code></pre>
</div>
<div id="renombramiento-de-variables" class="section level3 hasAnchor" number="2.3">
<h3><span class="header-section-number">2.3</span> Renombramiento de Variables<a href="#renombramiento-de-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para mayor practicidad, renombramos las columnas a nombres más cortos en español.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a><span class="fu">names</span>(df)[<span class="fu">names</span>(df) <span class="sc">==</span> <span class="st">&quot;Concrete compressive strength(MPa, megapascals)&quot;</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Resistencia_c&quot;</span></span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a><span class="fu">names</span>(df)[<span class="fu">names</span>(df) <span class="sc">==</span> <span class="st">&quot;Cement (component 1)(kg in a m^3 mixture)&quot;</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Cemento&quot;</span></span>
<span id="cb32-3"><a href="#cb32-3" tabindex="-1"></a><span class="fu">names</span>(df)[<span class="fu">names</span>(df) <span class="sc">==</span> <span class="st">&quot;Blast Furnace Slag (component 2)(kg in a m^3 mixture)&quot;</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Residuos&quot;</span></span>
<span id="cb32-4"><a href="#cb32-4" tabindex="-1"></a><span class="fu">names</span>(df)[<span class="fu">names</span>(df) <span class="sc">==</span> <span class="st">&quot;Fly Ash (component 3)(kg in a m^3 mixture)&quot;</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Cenizas&quot;</span></span>
<span id="cb32-5"><a href="#cb32-5" tabindex="-1"></a><span class="fu">names</span>(df)[<span class="fu">names</span>(df) <span class="sc">==</span> <span class="st">&quot;Water  (component 4)(kg in a m^3 mixture)&quot;</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Agua&quot;</span></span>
<span id="cb32-6"><a href="#cb32-6" tabindex="-1"></a><span class="fu">names</span>(df)[<span class="fu">names</span>(df) <span class="sc">==</span> <span class="st">&quot;Superplasticizer (component 5)(kg in a m^3 mixture)&quot;</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Superplastificante&quot;</span></span>
<span id="cb32-7"><a href="#cb32-7" tabindex="-1"></a><span class="fu">names</span>(df)[<span class="fu">names</span>(df) <span class="sc">==</span> <span class="st">&quot;Coarse Aggregate  (component 6)(kg in a m^3 mixture)&quot;</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Grueso&quot;</span></span>
<span id="cb32-8"><a href="#cb32-8" tabindex="-1"></a><span class="fu">names</span>(df)[<span class="fu">names</span>(df) <span class="sc">==</span> <span class="st">&quot;Fine Aggregate (component 7)(kg in a m^3 mixture)&quot;</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Fino&quot;</span></span>
<span id="cb32-9"><a href="#cb32-9" tabindex="-1"></a><span class="fu">names</span>(df)[<span class="fu">names</span>(df) <span class="sc">==</span> <span class="st">&quot;Age (day)&quot;</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Dias&quot;</span></span>
<span id="cb32-10"><a href="#cb32-10" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" tabindex="-1"></a><span class="fu">colnames</span>(df)</span></code></pre></div>
<pre><code>## [1] &quot;Cemento&quot;            &quot;Residuos&quot;           &quot;Cenizas&quot;           
## [4] &quot;Agua&quot;               &quot;Superplastificante&quot; &quot;Grueso&quot;            
## [7] &quot;Fino&quot;               &quot;Dias&quot;               &quot;Resistencia_c&quot;</code></pre>
<p>Prueba de Normalidad - Variable Objetivo</p>
<p>Verificamos si la variable Resistencia_c sigue una distribución normal usando la prueba de Kolmogorov-Smirnov.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a><span class="fu">ks.test</span>(df<span class="sc">$</span>Resistencia_c, <span class="st">&quot;pnorm&quot;</span>, <span class="at">mean =</span> <span class="fu">mean</span>(df<span class="sc">$</span>Resistencia_c), <span class="at">sd =</span> <span class="fu">sd</span>(df<span class="sc">$</span>Resistencia_c))</span></code></pre></div>
<pre><code>## Warning in ks.test.default(df$Resistencia_c, &quot;pnorm&quot;, mean =
## mean(df$Resistencia_c), : ties should not be present for the one-sample
## Kolmogorov-Smirnov test</code></pre>
<pre><code>## 
##  Asymptotic one-sample Kolmogorov-Smirnov test
## 
## data:  df$Resistencia_c
## D = 0.041303, p-value = 0.05954
## alternative hypothesis: two-sided</code></pre>
<p><strong>Conclusión:</strong> Nuestra variable resistencia no es normal.</p>
</div>
</div>
<div id="análisis-de-correlaciones" class="section level2 hasAnchor" number="3">
<h2><span class="header-section-number">3</span> Análisis de Correlaciones<a href="#an%C3%A1lisis-de-correlaciones" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="resistencia-vs-cemento" class="section level3 hasAnchor" number="3.1">
<h3><span class="header-section-number">3.1</span> Resistencia vs Cemento<a href="#resistencia-vs-cemento" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Gráfico de Dispersión</strong></p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Resistencia_c, <span class="at">y =</span> Cemento)) <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb37-4"><a href="#cb37-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">formula =</span> <span class="st">&#39;y~x&#39;</span>, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb37-5"><a href="#cb37-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb37-6"><a href="#cb37-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relación entre el cemento y la resistencia del concreto&quot;</span>,</span>
<span id="cb37-7"><a href="#cb37-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb37-8"><a href="#cb37-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Cemento&quot;</span></span>
<span id="cb37-9"><a href="#cb37-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb37-10"><a href="#cb37-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p><strong>Prueba de Normalidad - Cemento</strong></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Cemento)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Cemento
## D = 0.078553, p-value &lt; 2.2e-16</code></pre>
<p><strong>Conclusión:</strong> La variable cemento no es normal. El p-valor &lt; 0.05.</p>
<p>Como una de nuestras variables no es normal, debemos validar los supuestos de Spearman.</p>
<p><strong>Validación de Supuestos para Spearman</strong></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a><span class="co"># 1️⃣ Verifica que las variables sean numéricas</span></span>
<span id="cb40-2"><a href="#cb40-2" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Cemento)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Resistencia_c)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" tabindex="-1"></a><span class="co"># 2️⃣ Revisa valores faltantes</span></span>
<span id="cb44-2"><a href="#cb44-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Cemento))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Resistencia_c))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p><strong>Visualización de Correlación</strong></p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" tabindex="-1"></a><span class="co"># 3️⃣ Visualiza la relación</span></span>
<span id="cb48-2"><a href="#cb48-2" tabindex="-1"></a><span class="fu">ggscatter</span>(df, <span class="at">x =</span> <span class="st">&quot;Cemento&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb48-3"><a href="#cb48-3" tabindex="-1"></a>          <span class="at">add =</span> <span class="st">&quot;reg.line&quot;</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb48-4"><a href="#cb48-4" tabindex="-1"></a>          <span class="at">cor.coef =</span> <span class="cn">TRUE</span>, <span class="at">cor.method =</span> <span class="st">&quot;spearman&quot;</span>,</span>
<span id="cb48-5"><a href="#cb48-5" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Cemento&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Resistencia del concreto&quot;</span>,</span>
<span id="cb48-6"><a href="#cb48-6" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Dispersión y correlación (Spearman)&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" tabindex="-1"></a><span class="co"># 4️⃣ Verifica la forma de la relación (monótona)</span></span>
<span id="cb49-2"><a href="#cb49-2" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>Cemento, df<span class="sc">$</span>Resistencia_c, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb49-3"><a href="#cb49-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Verificación de relación monótona&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-19-2.png" width="672" /></p>
<p><strong>Prueba de Correlación de Spearman</strong></p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" tabindex="-1"></a><span class="co"># 5️⃣ Ejecuta la prueba de correlación de Spearman</span></span>
<span id="cb50-2"><a href="#cb50-2" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Cemento, df<span class="sc">$</span>Resistencia_c, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Cemento and df$Resistencia_c
## S = 95139797, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.4776012</code></pre>
</div>
<div id="resistencia-vs-residuos" class="section level3 hasAnchor" number="3.2">
<h3><span class="header-section-number">3.2</span> Resistencia vs Residuos<a href="#resistencia-vs-residuos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Gráfico de Dispersión</strong></p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="#cb52-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Resistencia_c, <span class="at">y =</span> Residuos)) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">formula =</span> <span class="st">&#39;y~x&#39;</span>, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb52-6"><a href="#cb52-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relación entre RESISTENCIA y los residuos&quot;</span>,</span>
<span id="cb52-7"><a href="#cb52-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb52-8"><a href="#cb52-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Residuos&quot;</span></span>
<span id="cb52-9"><a href="#cb52-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb52-10"><a href="#cb52-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p><strong>Prueba de Normalidad y Análisis</strong></p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Residuos)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Residuos
## D = 0.26135, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" tabindex="-1"></a><span class="co"># Verifica que las variables sean numéricas</span></span>
<span id="cb55-2"><a href="#cb55-2" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Residuos)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Resistencia_c)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" tabindex="-1"></a><span class="co"># Revisa valores faltantes</span></span>
<span id="cb59-2"><a href="#cb59-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Residuos))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Resistencia_c))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" tabindex="-1"></a><span class="co"># Visualiza la relación</span></span>
<span id="cb63-2"><a href="#cb63-2" tabindex="-1"></a><span class="fu">ggscatter</span>(df, <span class="at">x =</span> <span class="st">&quot;Residuos&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb63-3"><a href="#cb63-3" tabindex="-1"></a>          <span class="at">add =</span> <span class="st">&quot;reg.line&quot;</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb63-4"><a href="#cb63-4" tabindex="-1"></a>          <span class="at">cor.coef =</span> <span class="cn">TRUE</span>, <span class="at">cor.method =</span> <span class="st">&quot;spearman&quot;</span>,</span>
<span id="cb63-5"><a href="#cb63-5" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Residuos&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Resistencia del concreto&quot;</span>,</span>
<span id="cb63-6"><a href="#cb63-6" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Dispersión y correlación (Spearman)&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" tabindex="-1"></a><span class="co"># Verifica la forma de la relación (monótona)</span></span>
<span id="cb64-2"><a href="#cb64-2" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>Cemento, df<span class="sc">$</span>Resistencia_c, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb64-3"><a href="#cb64-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Verificación de relación monótona&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-22-2.png" width="672" /></p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" tabindex="-1"></a><span class="co"># Ejecuta la prueba de correlación de Spearman</span></span>
<span id="cb65-2"><a href="#cb65-2" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Cemento, df<span class="sc">$</span>Resistencia_c, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Cemento and df$Resistencia_c
## S = 95139797, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.4776012</code></pre>
</div>
<div id="resistencia-vs-cenizas" class="section level3 hasAnchor" number="3.3">
<h3><span class="header-section-number">3.3</span> Resistencia vs Cenizas<a href="#resistencia-vs-cenizas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Gráfico de Dispersión</strong></p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb67-2"><a href="#cb67-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Resistencia_c, <span class="at">y =</span> Cenizas)) <span class="sc">+</span></span>
<span id="cb67-3"><a href="#cb67-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb67-4"><a href="#cb67-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">formula =</span> <span class="st">&#39;y~x&#39;</span>, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb67-5"><a href="#cb67-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb67-6"><a href="#cb67-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relación entre RESISTENCIA Y las cenizas&quot;</span>,</span>
<span id="cb67-7"><a href="#cb67-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb67-8"><a href="#cb67-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Cenizas&quot;</span></span>
<span id="cb67-9"><a href="#cb67-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb67-10"><a href="#cb67-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p><strong>Prueba de Normalidad y Análisis</strong></p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Cenizas)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Cenizas
## D = 0.35094, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" tabindex="-1"></a><span class="co"># No hay normalidad, hacemos spearman, verificando supuestos</span></span>
<span id="cb70-2"><a href="#cb70-2" tabindex="-1"></a></span>
<span id="cb70-3"><a href="#cb70-3" tabindex="-1"></a><span class="co"># Verifica que las variables sean numéricas</span></span>
<span id="cb70-4"><a href="#cb70-4" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Cenizas)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Resistencia_c)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" tabindex="-1"></a><span class="co"># Revisa valores faltantes</span></span>
<span id="cb74-2"><a href="#cb74-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Cenizas))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Resistencia_c))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" tabindex="-1"></a><span class="co"># Visualiza la relación</span></span>
<span id="cb78-2"><a href="#cb78-2" tabindex="-1"></a><span class="fu">ggscatter</span>(df, <span class="at">x =</span> <span class="st">&quot;Cenizas&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb78-3"><a href="#cb78-3" tabindex="-1"></a>          <span class="at">add =</span> <span class="st">&quot;reg.line&quot;</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb78-4"><a href="#cb78-4" tabindex="-1"></a>          <span class="at">cor.coef =</span> <span class="cn">TRUE</span>, <span class="at">cor.method =</span> <span class="st">&quot;spearman&quot;</span>,</span>
<span id="cb78-5"><a href="#cb78-5" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Cenizas&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Resistencia del concreto&quot;</span>,</span>
<span id="cb78-6"><a href="#cb78-6" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Dispersión y correlación (Spearman)&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" tabindex="-1"></a><span class="co"># Verifica la forma de la relación (monótona)</span></span>
<span id="cb79-2"><a href="#cb79-2" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>Cenizas, df<span class="sc">$</span>Resistencia_c, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb79-3"><a href="#cb79-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Verificación de relación monótona&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-24-2.png" width="672" /></p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" tabindex="-1"></a><span class="co"># Ejecuta la prueba de correlación de Spearman</span></span>
<span id="cb80-2"><a href="#cb80-2" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Cenizas, df<span class="sc">$</span>Resistencia_c, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Cenizas and df$Resistencia_c
## S = 196318556, p-value = 0.01233
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##         rho 
## -0.07795675</code></pre>
</div>
<div id="resistencia-vs-agua" class="section level3 hasAnchor" number="3.4">
<h3><span class="header-section-number">3.4</span> Resistencia vs Agua<a href="#resistencia-vs-agua" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Gráfico de Dispersión</strong></p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb82-2"><a href="#cb82-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Resistencia_c, <span class="at">y =</span> Agua)) <span class="sc">+</span></span>
<span id="cb82-3"><a href="#cb82-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb82-4"><a href="#cb82-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">formula =</span> <span class="st">&#39;y~x&#39;</span>, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb82-5"><a href="#cb82-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb82-6"><a href="#cb82-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relación entre RESISTENCIA y AGUA&quot;</span>,</span>
<span id="cb82-7"><a href="#cb82-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb82-8"><a href="#cb82-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Agua&quot;</span></span>
<span id="cb82-9"><a href="#cb82-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb82-10"><a href="#cb82-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p><strong>Prueba de Normalidad y Análisis</strong></p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Agua)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Agua
## D = 0.073577, p-value = 2.404e-14</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" tabindex="-1"></a><span class="co"># No hay normalidad, hacemos spearman, verificando supuestos</span></span>
<span id="cb85-2"><a href="#cb85-2" tabindex="-1"></a></span>
<span id="cb85-3"><a href="#cb85-3" tabindex="-1"></a><span class="co"># Verifica que las variables sean numéricas</span></span>
<span id="cb85-4"><a href="#cb85-4" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Agua)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Resistencia_c)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" tabindex="-1"></a><span class="co"># Revisa valores faltantes</span></span>
<span id="cb89-2"><a href="#cb89-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Agua))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Resistencia_c))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" tabindex="-1"></a><span class="co"># Visualiza la relación</span></span>
<span id="cb93-2"><a href="#cb93-2" tabindex="-1"></a><span class="fu">ggscatter</span>(df, <span class="at">x =</span> <span class="st">&quot;Agua&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb93-3"><a href="#cb93-3" tabindex="-1"></a>          <span class="at">add =</span> <span class="st">&quot;reg.line&quot;</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb93-4"><a href="#cb93-4" tabindex="-1"></a>          <span class="at">cor.coef =</span> <span class="cn">TRUE</span>, <span class="at">cor.method =</span> <span class="st">&quot;spearman&quot;</span>,</span>
<span id="cb93-5"><a href="#cb93-5" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Agua&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Resistencia del concreto&quot;</span>,</span>
<span id="cb93-6"><a href="#cb93-6" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Dispersión y correlación (Spearman)&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" tabindex="-1"></a><span class="co"># Verifica la forma de la relación (monótona)</span></span>
<span id="cb94-2"><a href="#cb94-2" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>Agua, df<span class="sc">$</span>Resistencia_c, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb94-3"><a href="#cb94-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Verificación de relación monótona&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-26-2.png" width="672" /></p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" tabindex="-1"></a><span class="co"># Ejecuta la prueba de correlación de Spearman</span></span>
<span id="cb95-2"><a href="#cb95-2" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Agua, df<span class="sc">$</span>Resistencia_c, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Agua and df$Resistencia_c
## S = 238281768, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##        rho 
## -0.3083707</code></pre>
</div>
<div id="resistencia-vs-superplastificante" class="section level3 hasAnchor" number="3.5">
<h3><span class="header-section-number">3.5</span> Resistencia vs Superplastificante<a href="#resistencia-vs-superplastificante" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Gráfico de Dispersión</strong></p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb97-2"><a href="#cb97-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Resistencia_c, <span class="at">y =</span> Superplastificante)) <span class="sc">+</span></span>
<span id="cb97-3"><a href="#cb97-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb97-4"><a href="#cb97-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">formula =</span> <span class="st">&#39;y~x&#39;</span>, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb97-5"><a href="#cb97-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb97-6"><a href="#cb97-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relación entre RESISTENCIA y Superplastificante&quot;</span>,</span>
<span id="cb97-7"><a href="#cb97-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb97-8"><a href="#cb97-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Superplastificante&quot;</span></span>
<span id="cb97-9"><a href="#cb97-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb97-10"><a href="#cb97-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p><strong>Prueba de Normalidad y Análisis</strong></p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Superplastificante)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Superplastificante
## D = 0.21843, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" tabindex="-1"></a><span class="co"># No hay normalidad, hacemos spearman, verificando supuestos</span></span>
<span id="cb100-2"><a href="#cb100-2" tabindex="-1"></a></span>
<span id="cb100-3"><a href="#cb100-3" tabindex="-1"></a><span class="co"># Verifica que las variables sean numéricas</span></span>
<span id="cb100-4"><a href="#cb100-4" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Superplastificante)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Resistencia_c)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" tabindex="-1"></a><span class="co"># Revisa valores faltantes</span></span>
<span id="cb104-2"><a href="#cb104-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Superplastificante))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Resistencia_c))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" tabindex="-1"></a><span class="co"># Visualiza la relación</span></span>
<span id="cb108-2"><a href="#cb108-2" tabindex="-1"></a><span class="fu">ggscatter</span>(df, <span class="at">x =</span> <span class="st">&quot;Superplastificante&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb108-3"><a href="#cb108-3" tabindex="-1"></a>          <span class="at">add =</span> <span class="st">&quot;reg.line&quot;</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb108-4"><a href="#cb108-4" tabindex="-1"></a>          <span class="at">cor.coef =</span> <span class="cn">TRUE</span>, <span class="at">cor.method =</span> <span class="st">&quot;spearman&quot;</span>,</span>
<span id="cb108-5"><a href="#cb108-5" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Superplastificante&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Resistencia del concreto&quot;</span>,</span>
<span id="cb108-6"><a href="#cb108-6" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Dispersión y correlación (Spearman)&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" tabindex="-1"></a><span class="co"># Verifica la forma de la relación (monótona)</span></span>
<span id="cb109-2"><a href="#cb109-2" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>Superplastificante, df<span class="sc">$</span>Resistencia_c, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb109-3"><a href="#cb109-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Verificación de relación monótona&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-28-2.png" width="672" /></p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" tabindex="-1"></a><span class="co"># Ejecuta la prueba de correlación de Spearman</span></span>
<span id="cb110-2"><a href="#cb110-2" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Superplastificante, df<span class="sc">$</span>Resistencia_c, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Superplastificante and df$Resistencia_c
## S = 118817755, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.3475889</code></pre>
</div>
<div id="resistencia-vs-grueso" class="section level3 hasAnchor" number="3.6">
<h3><span class="header-section-number">3.6</span> Resistencia vs Grueso<a href="#resistencia-vs-grueso" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Gráfico de Dispersión</strong></p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb112-2"><a href="#cb112-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Resistencia_c, <span class="at">y =</span> Grueso)) <span class="sc">+</span></span>
<span id="cb112-3"><a href="#cb112-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb112-4"><a href="#cb112-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">formula =</span> <span class="st">&#39;y~x&#39;</span>, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb112-5"><a href="#cb112-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb112-6"><a href="#cb112-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relación entre RESISTENCIA y Grueso&quot;</span>,</span>
<span id="cb112-7"><a href="#cb112-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb112-8"><a href="#cb112-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Grueso&quot;</span></span>
<span id="cb112-9"><a href="#cb112-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb112-10"><a href="#cb112-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p><strong>Prueba de Normalidad y Análisis</strong></p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Grueso)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Grueso
## D = 0.063834, p-value = 1.252e-10</code></pre>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" tabindex="-1"></a><span class="co"># Verifica que las variables sean numéricas</span></span>
<span id="cb115-2"><a href="#cb115-2" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Grueso)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Resistencia_c)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" tabindex="-1"></a><span class="co"># Revisa valores faltantes</span></span>
<span id="cb119-2"><a href="#cb119-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Grueso))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Resistencia_c))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" tabindex="-1"></a><span class="co"># Visualiza la relación</span></span>
<span id="cb123-2"><a href="#cb123-2" tabindex="-1"></a><span class="fu">ggscatter</span>(df, <span class="at">x =</span> <span class="st">&quot;Grueso&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb123-3"><a href="#cb123-3" tabindex="-1"></a>          <span class="at">add =</span> <span class="st">&quot;reg.line&quot;</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb123-4"><a href="#cb123-4" tabindex="-1"></a>          <span class="at">cor.coef =</span> <span class="cn">TRUE</span>, <span class="at">cor.method =</span> <span class="st">&quot;spearman&quot;</span>,</span>
<span id="cb123-5"><a href="#cb123-5" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Grueso&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Resistencia del concreto&quot;</span>,</span>
<span id="cb123-6"><a href="#cb123-6" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Dispersión y correlación (Spearman)&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" tabindex="-1"></a><span class="co"># Verifica la forma de la relación (monótona)</span></span>
<span id="cb124-2"><a href="#cb124-2" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>Grueso, df<span class="sc">$</span>Resistencia_c, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb124-3"><a href="#cb124-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Verificación de relación monótona&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-30-2.png" width="672" /></p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" tabindex="-1"></a><span class="co"># Ejecuta la prueba de correlación de Spearman</span></span>
<span id="cb125-2"><a href="#cb125-2" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Grueso, df<span class="sc">$</span>Resistencia_c, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Grueso and df$Resistencia_c
## S = 215543059, p-value = 2.975e-09
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##        rho 
## -0.1835157</code></pre>
</div>
<div id="resistencia-vs-fino" class="section level3 hasAnchor" number="3.7">
<h3><span class="header-section-number">3.7</span> Resistencia vs Fino<a href="#resistencia-vs-fino" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Gráfico de Dispersión</strong></p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb127-2"><a href="#cb127-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Resistencia_c, <span class="at">y =</span> Fino)) <span class="sc">+</span></span>
<span id="cb127-3"><a href="#cb127-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb127-4"><a href="#cb127-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">formula =</span> <span class="st">&#39;y~x&#39;</span>, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb127-5"><a href="#cb127-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb127-6"><a href="#cb127-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relación entre RESISTENCIA y Fino&quot;</span>,</span>
<span id="cb127-7"><a href="#cb127-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb127-8"><a href="#cb127-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Fino&quot;</span></span>
<span id="cb127-9"><a href="#cb127-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb127-10"><a href="#cb127-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p><strong>Prueba de Normalidad y Análisis</strong></p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Fino)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Fino
## D = 0.085723, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" tabindex="-1"></a><span class="co"># Verifica que las variables sean numéricas</span></span>
<span id="cb130-2"><a href="#cb130-2" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Fino)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Resistencia_c)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" tabindex="-1"></a><span class="co"># Revisa valores faltantes</span></span>
<span id="cb134-2"><a href="#cb134-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Fino))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Resistencia_c))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" tabindex="-1"></a><span class="co"># Visualiza la relación</span></span>
<span id="cb138-2"><a href="#cb138-2" tabindex="-1"></a><span class="fu">ggscatter</span>(df, <span class="at">x =</span> <span class="st">&quot;Fino&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb138-3"><a href="#cb138-3" tabindex="-1"></a>          <span class="at">add =</span> <span class="st">&quot;reg.line&quot;</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb138-4"><a href="#cb138-4" tabindex="-1"></a>          <span class="at">cor.coef =</span> <span class="cn">TRUE</span>, <span class="at">cor.method =</span> <span class="st">&quot;spearman&quot;</span>,</span>
<span id="cb138-5"><a href="#cb138-5" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Fino&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Resistencia del concreto&quot;</span>,</span>
<span id="cb138-6"><a href="#cb138-6" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Dispersión y correlación (Spearman)&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" tabindex="-1"></a><span class="co"># Verifica la forma de la relación (monótona)</span></span>
<span id="cb139-2"><a href="#cb139-2" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>Fino, df<span class="sc">$</span>Resistencia_c, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb139-3"><a href="#cb139-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Verificación de relación monótona&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-32-2.png" width="672" /></p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" tabindex="-1"></a><span class="co"># Ejecuta la prueba de correlación de Spearman</span></span>
<span id="cb140-2"><a href="#cb140-2" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Fino, df<span class="sc">$</span>Resistencia_c, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Fino and df$Resistencia_c
## S = 214901130, p-value = 5.987e-09
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## -0.179991</code></pre>
</div>
<div id="resistencia-vs-dias" class="section level3 hasAnchor" number="3.8">
<h3><span class="header-section-number">3.8</span> Resistencia vs Dias<a href="#resistencia-vs-dias" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb142-2"><a href="#cb142-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Resistencia_c, <span class="at">y =</span>Dias )) <span class="sc">+</span></span>
<span id="cb142-3"><a href="#cb142-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>,<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb142-4"><a href="#cb142-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">formula =</span> <span class="st">&#39;y~x&#39;</span>, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="at">se =</span> <span class="cn">TRUE</span>,<span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb142-5"><a href="#cb142-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb142-6"><a href="#cb142-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relación entre RESISTENCIA y Dias&quot;</span>,</span>
<span id="cb142-7"><a href="#cb142-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb142-8"><a href="#cb142-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Dias&quot;</span></span>
<span id="cb142-9"><a href="#cb142-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb142-10"><a href="#cb142-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Dias)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Dias
## D = 0.33729, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" tabindex="-1"></a><span class="co"># 1️⃣ Verifica que las variables sean numéricas</span></span>
<span id="cb145-2"><a href="#cb145-2" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Dias)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" tabindex="-1"></a><span class="fu">is.numeric</span>(df<span class="sc">$</span>Resistencia_c)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" tabindex="-1"></a><span class="co"># 2️⃣ Revisa valores faltantes</span></span>
<span id="cb149-2"><a href="#cb149-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Dias))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>Resistencia_c))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" tabindex="-1"></a><span class="co"># 3️⃣ Visualiza la relación</span></span>
<span id="cb153-2"><a href="#cb153-2" tabindex="-1"></a><span class="fu">ggscatter</span>(df, <span class="at">x =</span> <span class="st">&quot;Dias&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Resistencia_c&quot;</span>,</span>
<span id="cb153-3"><a href="#cb153-3" tabindex="-1"></a>          <span class="at">add =</span> <span class="st">&quot;reg.line&quot;</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb153-4"><a href="#cb153-4" tabindex="-1"></a>          <span class="at">cor.coef =</span> <span class="cn">TRUE</span>, <span class="at">cor.method =</span> <span class="st">&quot;spearman&quot;</span>,</span>
<span id="cb153-5"><a href="#cb153-5" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Fino&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Resistencia del concreto&quot;</span>,</span>
<span id="cb153-6"><a href="#cb153-6" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Dispersión y correlación (Spearman)&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-33-2.png" width="672" /></p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="#cb154-1" tabindex="-1"></a><span class="co"># 4️⃣ Verifica la forma de la relación (monótona)</span></span>
<span id="cb154-2"><a href="#cb154-2" tabindex="-1"></a><span class="co"># Si la relación es creciente o decreciente, aunque no lineal, se puede usar Spearman</span></span>
<span id="cb154-3"><a href="#cb154-3" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>Dias, df<span class="sc">$</span>Resistencia_c, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb154-4"><a href="#cb154-4" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Verificación de relación monótona&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-33-3.png" width="672" /></p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" tabindex="-1"></a><span class="co"># 5️⃣ Ejecuta la prueba de correlación de Spearman</span></span>
<span id="cb155-2"><a href="#cb155-2" tabindex="-1"></a>resultado <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(df<span class="sc">$</span>Dias, df<span class="sc">$</span>Resistencia_c, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">exact=</span><span class="cn">FALSE</span>)</span>
<span id="cb155-3"><a href="#cb155-3" tabindex="-1"></a>resultado</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Dias and df$Resistencia_c
## S = 73573324, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.5960195</code></pre>
<p>Planteamos las hipótesis:</p>
<p><span class="math display">\[
H_0: \rho_S = 0 \quad \text{(no hay relación monótona)}
\]</span></p>
<p><span class="math display">\[
H_1: \rho_S \neq 0 \quad \text{(existe relación monótona)}
\]</span></p>
<p>Veamos:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(df)</span>
<span id="cb157-2"><a href="#cb157-2" tabindex="-1"></a>gl <span class="ot">=</span> n<span class="dv">-2</span></span>
<span id="cb157-3"><a href="#cb157-3" tabindex="-1"></a>p <span class="ot">=</span> resultado<span class="sc">$</span>estimate[[<span class="dv">1</span>]]</span>
<span id="cb157-4"><a href="#cb157-4" tabindex="-1"></a>t_critico <span class="ot">=</span> p<span class="sc">*</span><span class="fu">sqrt</span>(gl<span class="sc">/</span><span class="dv">1</span><span class="sc">-</span>p<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb157-5"><a href="#cb157-5" tabindex="-1"></a>t_critico <span class="ot">=</span> <span class="fu">abs</span>(t_critico)</span>
<span id="cb157-6"><a href="#cb157-6" tabindex="-1"></a>alpha <span class="ot">=</span> <span class="fl">0.05</span></span>
<span id="cb157-7"><a href="#cb157-7" tabindex="-1"></a>t_tab <span class="ot">=</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>,<span class="at">df=</span>gl)</span>
<span id="cb157-8"><a href="#cb157-8" tabindex="-1"></a><span class="fu">abs</span>(t_critico)</span></code></pre></div>
<pre><code>## [1] 19.10654</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" tabindex="-1"></a>t_tab</span></code></pre></div>
<pre><code>## [1] 1.962274</code></pre>
<p>El análisis de Spearman entre el contenido de <strong>dias</strong> y la <strong>resistencia del concreto</strong> mostró un coeficiente<br />
<span class="math display">\[
\rho_S = [0.5960195],
\]</span>
indicando una **correlación positica moderada*; con el aumento de los dias mejora la resistencia del concreto.
El estadístico de prueba permitió <strong>rechazar H₀</strong>, demostrando que la relación observada es <strong>estadísticamente significativa</strong>, puesto que nuestro t critico 19.106538 es mayor que el t en tabla 1.9622743.</p>
</div>
</div>
<div id="conclusiones" class="section level2 hasAnchor" number="4">
<h2><span class="header-section-number">4</span> Conclusiones<a href="#conclusiones" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Este documento presenta un análisis completo de las correlaciones entre la resistencia del concreto y sus diferentes componentes, utilizando pruebas de normalidad de Lilliefors y correlaciones de Spearman cuando las variables no siguen una distribución normal.</p>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/USERNAME/REPO/edit/BRANCH/%s",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": false,
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
